config/routes.rb
Marwan::Application.routes.draw do
  root "pages#home"
  get "contact" => "pages#contact"
  get "enquiry" => "pages#enquiry"
  get "news-events" => "pages#news_events", :as => 'news_events'
  get "brands" => "pages#brands"
  get "services" => "pages#services"
  get "cable-management" => "pages#cable_management", :as => 'cable_management'
  get "light-fitting" => "pages#light_fitting", :as => 'light_fitting'
  get "lighting-protection" => "pages#lighting_protection", :as => 'lighting_protection'
  get "company-profile" => "pages#company_profile", :as => 'company_profile'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def enquiry
  end

  def news_events
  end

  def brands
  end

  def services
  end

  def cable_management
  end

  def light_fitting
  end

  def lighting_protection
  end

  def company_profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	    <div class="container">
	    	<br>
	    	<div class="row">
	    		<div class="col-md-6">
	      		Call Us: <strong>+971-6-5335963; +971-2-5513121; +971-50-6463279</strong>
      		</div>
	    		<div class="col-md-6 text-muted credit" align="right">
	      		Copyright 2014 Marwan Electrical and Sanitary Ware Co. Ltd<br>
	      		All Rights Reserved.
      		</div>
      	</div>
	    </div>
	  </div>

app/views/layouts/_header.html.erb
<div id="banner">
 <% if Rails.env.production? %>
  <%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/marwan_header.JPG" %>
  <% else %>
  <%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/marwan_header.JPG" %>
  <% end %>
</div>

<nav class="navbar navbar-default" role="navigation" style="margin-top:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Marwan</a>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills nav-justified">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Company Profile', company_profile_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Products</a>
          <ul class="dropdown-menu">
            <!--<li><%= link_to 'Cable Management', cable_management_path %></li>
            <li class="divider"></li>-->
            <li><%= link_to 'Light Fittings', light_fitting_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Lighting Protection', lighting_protection_path %></li>
          </ul>
        </li>
        <li><%= link_to 'Brands', brands_path %></li>
        <li><%= link_to 'News & Events', news_events_path %></li>
        <li><%= link_to 'Enquiry', enquiry_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
     </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Marwan</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrap">
			<div class="container">
				<%= render "layouts/header" %>
				<%= yield %>
			</div>
		</div>
		<%= render "layouts/footer" %>
	</body>
</html>

app/views/pages/brands.html.erb
<% if Rails.env.production? %>
	<body id="body-font-color">
		</br><h1><small><center>Our Brands</h1></br>

		<table class="table table-bordered">
			<tbody>
				<tr>
					<td align="center" style="vertical-align: middle"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/marshall-logo.jpg"), "http://www.marshall-tufflex.com/", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/j-propster.gif"), "http://www.proepster.de", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/intech_logo.gif"), "http://www.intralinktechno.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/good-lite.gif"), "http://www.uli.com.my", :target => "_blank" %></td>
				</tr>
				<tr>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/burn.gif"), "http://www.royalsteel.co.th", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/bandit.gif"), "http://www.band-it-idex.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/lightining.gif"), "http://www.l-and-e.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/renora.gif"), "http://www.remora.net", :target => "_blank" %></td>
				</tr>
				<tr>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/negurosu.gif"), "http://www.negurosu.co.uk", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/conway_logo.gif"), "http://www.conway.com.my", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/supportcomms_logo.gif"), "http://www.supportcomms.co.uk", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("https://s3.amazonaws.com/JustABucket/marwan/assets/images/united-logo.gif"), "http://www.uli.com.my", :target => "_blank" %></td>
				</tr>
			</tbody>
		</table>
	</body>

<% else %>
	<body id="body-font-color">
		</br><h1><small><center>Our Brands</h1></br>

		<table class="table table-bordered">
			<tbody>
				<tr>
					<td align="center" style="vertical-align: middle"><%= link_to image_tag("marshall-logo.jpg"), "http://www.marshall-tufflex.com/", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("j-propster.gif"), "http://www.proepster.de", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("intech_logo.gif"), "http://www.intralinktechno.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("good-lite.gif"), "http://www.uli.com.my", :target => "_blank" %></td>
				</tr>
				<tr>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("burn.gif"), "http://www.royalsteel.co.th", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("bandit.gif"), "http://www.band-it-idex.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("lightining.gif"), "http://www.l-and-e.com", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("renora.gif"), "http://www.remora.net", :target => "_blank" %></td>
				</tr>
				<tr>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("negurosu.gif"), "http://www.negurosu.co.uk", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("conway_logo.gif"), "http://www.conway.com.my", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("supportcomms_logo.gif"), "http://www.supportcomms.co.uk", :target => "_blank" %></td>
					<td align="center" style="vertical-align: middle;"><%= link_to image_tag("united-logo.gif"), "http://www.uli.com.my", :target => "_blank" %></td>
				</tr>
			</tbody>
		</table>
	</body>
<% end %>

app/views/pages/cable_management.html.erb
<h1>Pages#cable-management</h1>
<p>Find me in app/views/pages/cable-management.html.erb</p>

app/views/pages/company_profile.html.erb
<body id="body-font-color">
	</br><h1><small><center>Company Profile</h1></br>
	<p class="lead">Marwan Electrical & Sanitaryware Co Ltd, with its corporate base in the Sharjah specialises in quality cable management systems and by providing a front line solution in all areas of cable supports and management. The company is dedicated to determine the needs of the customer and provide a complete, reliable and efficient solution by incorporating the best brands in its area of expertise and services. The vision of our company has always been to provide specialist services and products that serve the needs of our clients, architects, interior designers, consultants and contractors. Keeping the requirements of our clients, we supply products that are designed to offer undeniable level of reliability and performance.
	</p>
	<p class="lead">
	The company with nearly 25 years of experience in the industry is managed by a group of professionals having a vast experience in the UAE industry; we harness the latest technology to offer quality products. We have experiences in supplying cable management systems for some major projects and clients like ADNOC, ETISALAT, airport projects, palaces, multi storied commercial and residential buildings. The company continues to incorporate new ideas whilst drawing simultaneously on the experience, industry knowledge and customer loyalty built up over the years. We are committed to building and maintaining long term collaborative relationships with our suppliers and customers. The relationships are nurtured by being responsive to customers, keeping their interest paramount and always placing their needs first.
	</p>
	<p class="lead">
	We are pleased to assure that all the materials and products dealt by ourselves are of high quality matching any international brand and from reputed manufactures worldwide. We have established offices and warehouses in Abu Dhabi, Dubai, Sharjah and Ajman and a network of distributors in the country carrying a good quantity of stock normally good enough to cater a project both locally and internationally. We enhance easy accessibility and efficient service quality in order to provide increased satisfaction to our customers.
	</p>
</body>

app/views/pages/contact.html.erb
<body id="body-font-color">
<h1><small>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</body>

app/views/pages/enquiry.html.erb
<h1><small>Pages#enquiry</h1>
<p>Find me in app/views/pages/enquiry.html.erb</p>

app/views/pages/home.html.erb
<body id="body-font-color">
  <h1><small></h1> <!-- For some reason without this the footer font size becomes bigger -->
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <% if Rails.env.production? %>
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/Slide1.png" %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/Slide2.png" %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/Slide3.png" %>
          <div class="carousel-caption">
          </div>
        </div>
      </div>
    <% else %>
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "slide1.png" %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "slide2.png" %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "slide3.png" %>
          <div class="carousel-caption">
          </div>
        </div>
      </div>
    <% end %>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</body>

app/views/pages/light_fitting.html.erb
<body id="body-font-color">
	</br><h1><small><center>Light Fittings</h1></br>

	<h2>LIGHTING & EQUIPMENT PUBLIC CO. LTD</h2></br>

	<p class="lead">Lighting & Equipment Public company limited a Thailand based company manufacturers of fluorescent luminaries and Cable Trunking products. 
	</p>

	<p class="lead">At present, the company has developed a number of product brands. Each product brand is designated to each particular product group to emphasize that each product brand is specialized in a particular product group:
	</P>

	<p>
		<ul class="lead">
		  <li><strong>LUSO is specialized for fluorescent lighting luminaire.</strong></li>
		  <li><strong>LUMAX is fighting brand for all lighting luminaire.</strong></li>
		  <li><strong>OPTEX is specialized for interior lighting luminaire.</strong></li>
		  <li><strong>LITEX is specialized for industrial and outdoor lighting luminaire.</strong></li>
		  <li><strong>LANEX is specialized for landscape lighting luminaire.</strong></li>
		  <li><strong>HOMEX is specialized for home decorative lighting luminaire.</strong></li>
		  <li><strong>LAMEX is specialized for lamps, control gear/equipment and accessories.</strong></li>
		  <li><strong>SIGNEX is specialized for advertising light box, decorative lighting and LED lighting luminaries.</strong></li>
		</ul>
	</P>
	<p class="lead">For more details visit: <%= link_to "www.l-and-e.com", "http://www.l-and-e.com" %></P>
	</br>

	<hr color="#fffff"><br>

	<h2>UNITED U-LI GOODLITE SDN BHD.</h2></br>

	<p class="lead">Lighting is more than just illumination of commercial or private space. Uli Group's vast array of lights and lighting accessories can be combined in a variety of ways to contribute to business image and productivity. Main Products: Fluorescent Light Fittings for office & residential applications.
	</p>
	<p class="lead">For more details visit: <%= link_to "www.uli.com.my	", "http://www.uli.com.my" %></P>
</body>

app/views/pages/lighting_protection.html.erb
<body id="body-font-color">
	</br><h1><small><center>Lighting Protection</h1></br>

	<h2>J Propster GmBH</h2>

	<% if Rails.env.production? %>
		<p align="center"><%= image_tag "https://s3.amazonaws.com/JustABucket/marwan/assets/images/propster.jpg" %></p>
	<% else %>
		<p align="center"><%= image_tag "propster.jpg" %></p>
	
	<% end %>

	<p class="lead"><strong>“With safety always one idea ahead!”</strong>. His slogan has been the motive for J. Pröpster and his team for the last 25 years of developing and manufacturing lightning protection components. The revolutionary ideas of J. Pröpster including numerous inventions and patents have been a major influence on the lightning protection industry. 

	The following systems are some of the innovative highlights developed by J. Pröpster:
	</p>

	<p>
		<table class="table table-bordered table-nonfluid" align="center">
			<tbody>
				<tr>
					<td>Original Multi-Clamp</td>
					<td>Optimal Intersection Rod</td>
				</tr>	
				<tr>
					<td>Vario-Clamp</td>
					<td>DUO Gutter Contact Clamp</td>
				</tr>
				<tr>
					<td>Bimetalclamp</td>
					<td>Roof Conductor Support with Clamping Device</td>
				</tr>
				<tr>
					<td>USV-Connection Clamp</td>
					<td>PRÖ-Color Components</td>
				</tr>
				<tr>
					<td>Diagonal-Cross-Clamp</td>
					<td>Lead-in Earhing Rod with Insulated Terminal</td>
				</tr>
				<tr>
					<td>Niro-Clip-Snap-on Holder</td>
					<td>Fixed Earthing Terminal</td>
				</tr>
				<tr>
					<td>Trapezoidal Support</td>
					<td>P-BM (smallest lightning current arrester 35 KA)</td>
				</tr>
				<tr>
					<td>ÖKO Flat Roof Support</td>
					<td>ISO-Stabil for insulated or partially ins. Protection</td>
				</tr>
			</tbody>
		</table>
	</p>

	<p class="lead">For more details visit: <%= link_to "www.proepster.de", "http://www.proepster.de"%></p>
</body>

app/views/pages/news_events.html.erb
<h1><small>Pages#news-events</h1>
<p>Find me in app/views/pages/news-events.html.erb</p>

app/views/pages/services.html.erb
<h1><small>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>